# Generated by Django 4.2.13 on 2024-07-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=20000)),
            ],
        ),
    ]
