# Generated by Django 4.2.13 on 2024-07-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_features_feature_rename_sports_sport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=200000)),
            ],
            options={
                'verbose_name_plural': 'lifestyle',
            },
        ),
        migrations.CreateModel(
            name='science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=200000)),
            ],
        ),
    ]
