# Generated by Django 4.2.13 on 2024-07-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/% d/'),
        ),
    ]
