# Generated by Django 4.2.13 on 2024-07-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_news_main_image_news_image_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
