# Generated by Django 4.2.13 on 2024-07-19 04:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_news_main_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'arts',
            },
        ),
        migrations.CreateModel(
            name='Life_culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Life',
            },
        ),
        migrations.DeleteModel(
            name='lifestyle',
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name_plural': 'features'},
        ),
        migrations.AlterModelOptions(
            name='opinion',
            options={'verbose_name_plural': 'opinions'},
        ),
        migrations.AlterModelOptions(
            name='science',
            options={'verbose_name_plural': 'science'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name_plural': 'sports'},
        ),
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='feature',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opinion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='science',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='science',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='sport',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='science',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='sport',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
